platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'ImagePickerDemo' do
	pod 'ImagePicker', path: '../../'
  pod 'iOSPhotoEditor'
#	pod 'Lightbox', git: 'https://github.com/hyperoslo/Lightbox.git'
	pod 'Sugar', git: 'https://github.com/hyperoslo/Sugar.git'
	pod 'Hue', git: 'https://github.com/hyperoslo/Hue.git'
end
